import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

import Header2 from "@/components/header2";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Detail",
    description: "Generated by Saurabh",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased`}
            >
                <Header2 />
                {children}
            </body>
        </html>
    );
}
