import { Metadata } from "next";


export const metadata: Metadata = {
    title: "Installation",
    description: "Generated by Saurabh",
};

export default function Installation() {
    return (
        <div className="flex bg-slate-700 h-screen p-4">
            <div className="flex flex-col gap-4">
                <h1>Installation</h1>
                <div className="flex flex-col gap-2">
                    <p>
                        Automatic installation
                    </p>
                    <span>
                        The quickest way to create a new Next.js
                        app is using create-next-app, which sets
                        up everything automatically for you. To create a
                        project, run:
                    </span>
                    <span>
                        <p>terminal</p>
                        npx create-next-app@latest
                    </span>
                </div>
                <div className="flex flex-col ">
                    <p>Terminal</p>
                    <ol>
                        <li>What is your project named? my-app</li>
                        <li>Would you like to use TypeScript? No / Yes</li>
                        <li>Would you like to use ESLint? No / Yes</li>
                        <li>Would you like to use Tailwind CSS? No / Yes</li>
                        <li>Would you like your code inside a `src/` directory? No / Yes</li>
                        <li>Would you like to use App Router? (recommended) No / Yes</li>
                        <li>Would you like to use Turbopack for `next dev`?  No / Yes</li>
                        <li>Would you like to customize the import alias (`@/*` by default)? No / Yes</li>
                        <li>What import alias would you like configured? @/*</li>
                    </ol>
                </div>
            </div>
        </div>
    );
}