export const sampleData = {
    "login": "saurabhkr21",
    "id": 120084606,
    "node_id": "U_kgDOByhYfg",
    "avatar_url": "https://avatars.githubusercontent.com/u/120084606?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/saurabhkr21",
    "html_url": "https://github.com/saurabhkr21",
    "followers_url": "https://api.github.com/users/saurabhkr21/followers",
    "following_url": "https://api.github.com/users/saurabhkr21/following{/other_user}",
    "gists_url": "https://api.github.com/users/saurabhkr21/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/saurabhkr21/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/saurabhkr21/subscriptions",
    "organizations_url": "https://api.github.com/users/saurabhkr21/orgs",
    "repos_url": "https://api.github.com/users/saurabhkr21/repos",
    "events_url": "https://api.github.com/users/saurabhkr21/events{/privacy}",
    "received_events_url": "https://api.github.com/users/saurabhkr21/received_events",
    "type": "User",
    "user_view_type": "public",
    "site_admin": false,
    "name": "Saurabh Kumar",
    "company": null,
    "blog": "",
    "location": null,
    "email": null,
    "hireable": null,
    "bio": "Reliance Scholar",
    "twitter_username": null,
    "public_repos": 5,
    "public_gists": 0,
    "followers": 0,
    "following": 0,
    "created_at": "2022-12-08T06:54:42Z",
    "updated_at": "2025-04-20T08:32:12Z"
}